[package]
name = "progenitor-client"
version = "0.5.1-alpha1"
edition = "2021"
license = "MPL-2.0"
repository = "https://github.com/oxidecomputer/progenitor.git"
description = "An OpenAPI client generator - client support"

[dependencies]
bytes = "1.5.0"
futures-core = "0.3.30"
percent-encoding = "2.3"
reqwest = { version = "0.11.22", default-features = false, features = ["json", "stream"] }
reqwest-middleware = "0.2.0"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.7.1"
